/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comic;

import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Acek
 */
public class DashboardMember extends javax.swing.JFrame {

    /**
     * Creates new form DashboardMember
     */
    public DashboardMember() {
        initComponents();
    }
    
    public void setTooltipsPeminjaman (String notif){
        jbPeminjaman.setToolTipText(notif);
    }
    public void setTooltipsStatus (String notif){
        jbViewValidasi.setToolTipText(notif);
    }
    
    public void listenerPeminjaman(ActionListener X) {
        jbPeminjaman.addActionListener(X);
    }
    public void listenerViewValidasi(ActionListener x){
        jbViewValidasi.addActionListener(x);
    }
    
    public void setImage(ImageIcon x) {
        LviewImage.setIcon(x);
    }
    public void setImage1(ImageIcon x) {
        LviewImage1.setIcon(x);
    }
    public void setImage2(ImageIcon x) {
        LviewImage2.setIcon(x);
    }
    public void setImage3(ImageIcon x) {
        LviewImage3.setIcon(x);
    }
    public void setImage4(ImageIcon x) {
        LviewImage4.setIcon(x);
    }
    public void setImage5(ImageIcon x) {
        LviewImage5.setIcon(x);
    }

     public void listenerExit(ActionListener x) {
        Jbexit.addActionListener(x);
    }
         public void listenerLogout (ActionListener x){
        jbLogout.addActionListener(x);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPeminjaman = new javax.swing.JButton();
        LviewImage = new javax.swing.JLabel();
        Jbexit = new javax.swing.JButton();
        jbLogout = new javax.swing.JButton();
        jbViewValidasi = new javax.swing.JButton();
        LviewImage5 = new javax.swing.JLabel();
        LviewImage4 = new javax.swing.JLabel();
        LviewImage3 = new javax.swing.JLabel();
        LviewImage1 = new javax.swing.JLabel();
        LviewImage2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbPeminjaman.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jbPeminjaman.setForeground(new java.awt.Color(0, 0, 0));
        jbPeminjaman.setText("Peminjaman");
        jbPeminjaman.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbPeminjaman.setContentAreaFilled(false);
        jbPeminjaman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jbPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, 90, 40));
        getContentPane().add(LviewImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 120, 180));

        Jbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit putih.png"))); // NOI18N
        Jbexit.setBorderPainted(false);
        Jbexit.setContentAreaFilled(false);
        Jbexit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit hitam.png"))); // NOI18N
        getContentPane().add(Jbexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jbLogout.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jbLogout.setForeground(new java.awt.Color(255, 255, 255));
        jbLogout.setText("Log out");
        jbLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbLogout.setBorderPainted(false);
        jbLogout.setContentAreaFilled(false);
        jbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jbLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, 30));

        jbViewValidasi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jbViewValidasi.setForeground(new java.awt.Color(0, 0, 0));
        jbViewValidasi.setText("View Status Validasi");
        jbViewValidasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbViewValidasi.setContentAreaFilled(false);
        jbViewValidasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jbViewValidasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 150, 40));
        getContentPane().add(LviewImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 120, 180));
        getContentPane().add(LviewImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 120, 170));
        getContentPane().add(LviewImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 120, 170));
        getContentPane().add(LviewImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 120, 180));
        getContentPane().add(LviewImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 120, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/member/DasborMember.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbexit;
    private javax.swing.JLabel LviewImage;
    private javax.swing.JLabel LviewImage1;
    private javax.swing.JLabel LviewImage2;
    private javax.swing.JLabel LviewImage3;
    private javax.swing.JLabel LviewImage4;
    private javax.swing.JLabel LviewImage5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbLogout;
    private javax.swing.JButton jbPeminjaman;
    private javax.swing.JButton jbViewValidasi;
    // End of variables declaration//GEN-END:variables
}
