/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comic;

import java.awt.event.ActionListener;
import models.koneksi;

/**
 *
 * @author Acek
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    koneksi sambung;

    public login() {
        initComponents();
        setLocationRelativeTo(null);
        sambung = new koneksi("komik", "root", "");
    }

        public String getUserName() {
        return TfUsername.getText();
    }

    public void setUserName(String X) {
        TfUsername.setText(X);
    }

    public String getUserPass() {
        return TfPass.getText();
    }

    public void setUserPass(String X) {
        TfPass.setText(X);
    }
    
    public void setNotif (String x){
        notif.setText(x);
    }

    public void listenerLogIn(ActionListener X) {
        JbLogin.addActionListener(X);
    }

    public void listenerExit(ActionListener X) {
        Jbexit.addActionListener(X);
    }
    
    public  void listenerRegister (ActionListener x){
        JbReg.addActionListener(x);
    }
        public void setTooltips (String x) {
        JbReg.setToolTipText(x);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jbexit = new javax.swing.JButton();
        JbLogin = new javax.swing.JButton();
        TfUsername = new javax.swing.JTextField();
        notif = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JbReg = new javax.swing.JButton();
        TfPass = new javax.swing.JPasswordField();
        backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit hitam.png"))); // NOI18N
        Jbexit.setBorderPainted(false);
        Jbexit.setContentAreaFilled(false);
        Jbexit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit putih.png"))); // NOI18N
        getContentPane().add(Jbexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        JbLogin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        JbLogin.setForeground(new java.awt.Color(255, 255, 255));
        JbLogin.setText("LOGIN");
        JbLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JbLogin.setContentAreaFilled(false);
        JbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(JbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 120, 40));

        TfUsername.setBackground(new java.awt.Color(0, 51, 51));
        TfUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TfUsername.setForeground(new java.awt.Color(255, 255, 255));
        TfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 300, 40));

        notif.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        notif.setForeground(new java.awt.Color(255, 255, 255));
        notif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 300, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Belum punya akun?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, 20));

        JbReg.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JbReg.setForeground(new java.awt.Color(255, 255, 255));
        JbReg.setText("Register");
        JbReg.setBorderPainted(false);
        JbReg.setContentAreaFilled(false);
        JbReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRegActionPerformed(evt);
            }
        });
        getContentPane().add(JbReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 80, 20));

        TfPass.setBackground(new java.awt.Color(0, 51, 51));
        TfPass.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TfPass.setForeground(new java.awt.Color(255, 255, 255));
        TfPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(TfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 300, 40));

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/all.png"))); // NOI18N
        backgroud.setToolTipText("");
        getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbLogin;
    private javax.swing.JButton JbReg;
    private javax.swing.JButton Jbexit;
    private javax.swing.JPasswordField TfPass;
    private javax.swing.JTextField TfUsername;
    private javax.swing.JLabel backgroud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel notif;
    // End of variables declaration//GEN-END:variables
}
