/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comic;

import controller.controlRegister;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;

/**
 *
 * @author Acek
 */
public class register extends javax.swing.JFrame {

    public register() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public void setTfKTP(String x) {
        TfKTP.setText(x);
    }

    public String getTfKTP() {
        return TfKTP.getText();
    }

    public void setTfNama(String x) {
        TfNama.setText(x);
    }

    public String getTfNama() {
        return TfNama.getText();
    }

    public String getJenis() {
        return cbJenis.getSelectedItem().toString();
    }

    public void setPekerjaan(String x) {
        TfPekerjaan.setText(x);
    }

    public String getPekerjaan() {
        return TfPekerjaan.getText();
    }

    public String gettanggal() {
       SimpleDateFormat formatdate;
        formatdate = new SimpleDateFormat("yyyy-M-d");
        String tgl = formatdate.format(jDate.getDate());
        return tgl;
    }

    public void setAlamat(String a) {
        AlamatText.setText(a);
    }

    public String getAlamat() {
        return AlamatText.getText();
    }

    public void setUsername(String a) {
        Tfuser.setText(a);
    }

    public String getUsername() {
        return Tfuser.getText();
    }

    public void setPassword(String a) {
        TpPass.setText(a);
    }

    public String getPassword() {
        return TpPass.getText();
    }

    public void listenerRegister(ActionListener x) {
        JbReg.addActionListener(x);
    }

    public void listenerExit(ActionListener x) {
        Jbexit.addActionListener(x);
    }
    
    public void listenerLogin (ActionListener x){
        JbLog.addActionListener(x);
    }
    
    public void notif (String x){
        notif.setText(x);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JbReg = new javax.swing.JButton();
        Jbexit = new javax.swing.JButton();
        Lktp = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        Ltgl1 = new javax.swing.JLabel();
        Ljenis = new javax.swing.JLabel();
        Lpekerjaan = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Luser = new javax.swing.JLabel();
        Lpass = new javax.swing.JLabel();
        JbLog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TfKTP = new javax.swing.JTextField();
        TfNama = new javax.swing.JTextField();
        jDate = new com.toedter.calendar.JDateChooser();
        cbJenis = new javax.swing.JComboBox<>();
        TfPekerjaan = new javax.swing.JTextField();
        TaAlamat = new javax.swing.JScrollPane();
        AlamatText = new javax.swing.JTextArea();
        Tfuser = new javax.swing.JTextField();
        TpPass = new javax.swing.JPasswordField();
        notif = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("REGISTRATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 40));

        JbReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/register.png"))); // NOI18N
        JbReg.setText("jButton1");
        JbReg.setBorderPainted(false);
        JbReg.setContentAreaFilled(false);
        JbReg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/register gelap.png"))); // NOI18N
        JbReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbRegActionPerformed(evt);
            }
        });
        getContentPane().add(JbReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 100, 40));

        Jbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit putih.png"))); // NOI18N
        Jbexit.setBorderPainted(false);
        Jbexit.setContentAreaFilled(false);
        Jbexit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/exit hitam.png"))); // NOI18N
        getContentPane().add(Jbexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        Lktp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Lktp.setForeground(new java.awt.Color(0, 0, 0));
        Lktp.setText("No. KTP");
        getContentPane().add(Lktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        Lnama.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Lnama.setForeground(new java.awt.Color(0, 0, 0));
        Lnama.setText("Nama");
        getContentPane().add(Lnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        Ltgl1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ltgl1.setForeground(new java.awt.Color(0, 0, 0));
        Ltgl1.setText("Tanggal Lahir");
        getContentPane().add(Ltgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        Ljenis.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Ljenis.setForeground(new java.awt.Color(0, 0, 0));
        Ljenis.setText("Jenis Kelamin");
        getContentPane().add(Ljenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        Lpekerjaan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Lpekerjaan.setForeground(new java.awt.Color(0, 0, 0));
        Lpekerjaan.setText("Pekerjaan");
        getContentPane().add(Lpekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        Lalamat.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Lalamat.setForeground(new java.awt.Color(0, 0, 0));
        Lalamat.setText("Alamat");
        getContentPane().add(Lalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        Luser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Luser.setForeground(new java.awt.Color(0, 0, 0));
        Luser.setText("Usename");
        getContentPane().add(Luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        Lpass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        Lpass.setForeground(new java.awt.Color(0, 0, 0));
        Lpass.setText("Password");
        getContentPane().add(Lpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, 20));

        JbLog.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JbLog.setForeground(new java.awt.Color(0, 153, 204));
        JbLog.setText("Log in");
        JbLog.setBorderPainted(false);
        JbLog.setContentAreaFilled(false);
        JbLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(JbLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 80, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Sudah punya akun?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, 20));
        getContentPane().add(TfKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 240, -1));
        getContentPane().add(TfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 240, -1));
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 240, -1));

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        getContentPane().add(cbJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 240, -1));
        getContentPane().add(TfPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 240, -1));

        AlamatText.setColumns(20);
        AlamatText.setRows(5);
        TaAlamat.setViewportView(AlamatText);

        getContentPane().add(TaAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 240, 100));
        getContentPane().add(Tfuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 240, -1));
        getContentPane().add(TpPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 240, -1));

        notif.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        notif.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 220, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginAndReg/registation.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AlamatText;
    private javax.swing.JButton JbLog;
    private javax.swing.JButton JbReg;
    private javax.swing.JButton Jbexit;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Ljenis;
    private javax.swing.JLabel Lktp;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lpass;
    private javax.swing.JLabel Lpekerjaan;
    private javax.swing.JLabel Ltgl1;
    private javax.swing.JLabel Luser;
    private javax.swing.JScrollPane TaAlamat;
    private javax.swing.JTextField TfKTP;
    private javax.swing.JTextField TfNama;
    private javax.swing.JTextField TfPekerjaan;
    private javax.swing.JTextField Tfuser;
    private javax.swing.JPasswordField TpPass;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> cbJenis;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel notif;
    // End of variables declaration//GEN-END:variables
}
